// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/incService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncCount int32 `protobuf:"varint,1,opt,name=incCount,proto3" json:"incCount,omitempty"`
}

func (x *IncMessage) Reset() {
	*x = IncMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_incService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncMessage) ProtoMessage() {}

func (x *IncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_incService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncMessage.ProtoReflect.Descriptor instead.
func (*IncMessage) Descriptor() ([]byte, []int) {
	return file_proto_incService_proto_rawDescGZIP(), []int{0}
}

func (x *IncMessage) GetIncCount() int32 {
	if x != nil {
		return x.IncCount
	}
	return 0
}

type IncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentCount int32 `protobuf:"varint,1,opt,name=currentCount,proto3" json:"currentCount,omitempty"`
}

func (x *IncResponse) Reset() {
	*x = IncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_incService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncResponse) ProtoMessage() {}

func (x *IncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_incService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncResponse.ProtoReflect.Descriptor instead.
func (*IncResponse) Descriptor() ([]byte, []int) {
	return file_proto_incService_proto_rawDescGZIP(), []int{1}
}

func (x *IncResponse) GetCurrentCount() int32 {
	if x != nil {
		return x.CurrentCount
	}
	return 0
}

var File_proto_incService_proto protoreflect.FileDescriptor

var file_proto_incService_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x28, 0x0a, 0x0a, 0x49, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x6e, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x69, 0x6e, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x31, 0x0a, 0x0b, 0x49, 0x6e, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x43, 0x0a, 0x0b,
	0x43, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x69,
	0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x49, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x3b, 0x5a, 0x39, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x63, 0x61, 0x72, 0x6c, 0x39,
	0x2f, 0x4f, 0x6e, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x2f, 0x53, 0x6b, 0x72, 0x69, 0x76, 0x65,
	0x62, 0x6f, 0x72, 0x64, 0x2f, 0x64, 0x69, 0x73, 0x79, 0x73, 0x4d, 0x4f, 0x43, 0x4b, 0x2f, 0x44,
	0x49, 0x53, 0x59, 0x53, 0x6d, 0x6f, 0x63, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_incService_proto_rawDescOnce sync.Once
	file_proto_incService_proto_rawDescData = file_proto_incService_proto_rawDesc
)

func file_proto_incService_proto_rawDescGZIP() []byte {
	file_proto_incService_proto_rawDescOnce.Do(func() {
		file_proto_incService_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_incService_proto_rawDescData)
	})
	return file_proto_incService_proto_rawDescData
}

var file_proto_incService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_incService_proto_goTypes = []interface{}{
	(*IncMessage)(nil),  // 0: proto.IncMessage
	(*IncResponse)(nil), // 1: proto.IncResponse
}
var file_proto_incService_proto_depIdxs = []int32{
	0, // 0: proto.ChatService.increment:input_type -> proto.IncMessage
	1, // 1: proto.ChatService.increment:output_type -> proto.IncResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_incService_proto_init() }
func file_proto_incService_proto_init() {
	if File_proto_incService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_incService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_incService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_incService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_incService_proto_goTypes,
		DependencyIndexes: file_proto_incService_proto_depIdxs,
		MessageInfos:      file_proto_incService_proto_msgTypes,
	}.Build()
	File_proto_incService_proto = out.File
	file_proto_incService_proto_rawDesc = nil
	file_proto_incService_proto_goTypes = nil
	file_proto_incService_proto_depIdxs = nil
}
